/*
  # Add world events to episode analyses

  1. Schema Changes
    - Add `world_events` (jsonb) column to `episode_analyses` table
    - Stores parallel historical events that occurred at the same time as timeline events
    - Each world event contains: date, event description, and category
    
  2. Indexes
    - Add GIN index on world_events for efficient JSONB queries
    
  3. Notes
    - Default to empty array for backward compatibility
    - World events are generated by AI to match timeline event dates
    - Provides historical context for podcast timeline events
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'episode_analyses' AND column_name = 'world_events'
  ) THEN
    ALTER TABLE episode_analyses ADD COLUMN world_events jsonb DEFAULT '[]'::jsonb;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_episode_analyses_world_events ON episode_analyses USING GIN (world_events);